/*
A program which returns the value of the nth element of the Fibonacci sequence.

Examples:
for fib(5) == 5
for fib(10) == 55

*/
#include<stdio.h>
using namespace std;
int fib(int n){

B:
/*
A program which returns the value of the nth element of the sequence generated by the formula

a(n) = a(n-1) + a(n-2) - 1

with a(0) = a(1) = 1

Examples:
for seq(5) == 6
for seq(10) == 29

*/
#include<stdio.h>
using namespace std;
int seq(int n){

C:
/*
A program which returns the value of the nth element of the sequence generated by the formula

a(n) = a(n-1) * a(n-2) + 2

with a(0) = a(1) = 1

Examples:
for seq(5) == 22
for seq(10) == 798

*/
#include<stdio.h>
using namespace std;
int seq(int n){

D:
/*
A program which returns the value of the nth element of the sequence generated by the formula

a(n) = a(n-1) * a(n-2) + a(n-3) + a(n-4)

with a(0) = a(1) = a(2) = a(3) = 1

Examples:
for seq(5) == 14
for seq(10) == 4156

*/
#include<stdio.h>
using namespace std;
int seq(int n){

E:
/*
A program which returns the value of the nth element of the sequence generated by the formula

a(n) = a(n-1) + a(n-2) - a(n-3) + a(n-4)

with a(0) = a(1) = a(2) = a(3) = 1

Examples:
for seq(5) == 5
for seq(10) == 5

*/
#include<stdio.h>
using namespace std;
int seq(int n){

F:
/*
A program which returns the value of the nth element of the sequence generated by the formula

a(n) = a(n-1) * a(n-2) + a(n-3) * a(n-4)

with a(0) = a(1) = a(2) = a(3) = 1