
def check_Consecutive(lst):
    return sorted(lst) == list(range(min(lst), max(lst)+1))

print(check_Consecutive([1,2,3,4,5]))

"""
This function first sorts the input list and then compares it with a list generated by using the range() function with the minimum and maximum elements of the input list as the start and end points. If the sorted list is equal to the list generated by range, then the function returns True, else it returns False.
"""

"""
