
// Given a positive integer, convert it to a Roman numeral.
// Input: 4
// Output: "IV"
// Input: 9
// Output: "IX"
// Input: 12
// Output: "XII"
// Input: 19
// Output: "XIX"
// Input: 49
// Output: "XLIX"
// Input: 59
// Output: "LIX"
// Input: 99
// Output: "XCIX"
// Input: 44
// Output: "XLIV"
// Input: 88
// Output: "LXXXVIII"
// Input: 66
// Output: "LXVI"
// Input: 1
// Output: "I"
// Input: 5
// Output: "V"
// Input: 9
// Output: "IX"
// Input: 12
// Output: "XII"
// Input: 19
// Output: "XIX"
// Input: 49
// Output: "XLIX"
// Input: 59
// Output: "LIX"
// Input: 99
// Output: "XCIX"
// Input: 44
// Output: "XLIV"
// Input: 88
// Output: "LXXXVIII"
// Input: 66
// Output: "LXVI"
// Input: 1
// Output: "I"
// Input: 5
// Output: "V"
// Input: 9
// Output: "IX"
// Input: 12
// Output: "XII"
// Input: 19
// Output: "XIX"
// Input: 49
// Output: "XLIX"
// Input: 59
// Output: "LIX"
// Input: 99
// Output: "XCIX"
// Input: 44
// Output: "XLIV"
// Input: 88
// Output: "LXXXVIII"
// Input: 66
// Output: "LXVI"
// Input: 1
// Output: "I"
//