    float num=atof(value.c_str());
    int integer=int(num);
    if (num-int(num)>0.5)
    return integer+1;
    else if (num-int(num)<0.5)
    return integer;
    else if (num>0)
    return integer+1;
    else
    return integer-1;
}  // End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest_integer function.// End of closest