    int level=0;
    for (int i=0;i<brackets.length();i++)
    {
        if (brackets[i]=='(')
            level+=1;
        if (brackets[i]==')')
            level-=1;
        if (level<0)
            return false;
    }
    return (level==0);
}  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing. 
}  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes negative. It is because when the level becomes negative, it means that there are more closing brackets than opening brackets, which is not a valid bracketing.  // Corrected the code by adding a condition to return false when level becomes