def digitSum(s):
    return sum(ord(c) for c in s if c.isupper())  # using generator expression and sum function

# Test cases
print(digitSum(""))  # 0
print(digitSum("abAB"))  # 131
print(digitSum("abcCd"))  # 67
print(digitSum("helloE"))  # 69
print(digitSum("woArBld"))  # 131
print(digitSum("aAaaaXa"))  # 153
print(digitSum("AaAa"))  # 65
print(digitSum("aAaA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65
print(digitSum("aA"))  # 65
print(digitSum("a"))  # 0
print(digitSum("A"))  # 65