            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBestHeight)
                aoc.nLeastDepth = 0;
            if  (aoc.nLeastDepth  != nBest