    int i;
    int largest_index=-1;
    for (i=1;i<arr.size();i++)
    {
        if (arr[i-1]<=arr[i])
        {
            largest_index=i-1;
            break;
        }
    }
    return largest_index;
}  // Please note that this function is case-sensitive. If you want to ignore case, you can convert both strings to lower case or upper case before comparison.  // This function will return the index of the first element in the array that is less than the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is less than the previous element. If no such element exists, it will return -1.  // This function will return the index of the first element in the array that is greater than the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is greater than the previous element. If no such element exists, it will return -1.  // This function will return the index of the first element in the array that is equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the first element in the array that is less than or equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is less than or equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the first element in the array that is greater than or equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is greater than or equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the first element in the array that is equal to the previous element. If no such element exists, it will return -1.  // This function will return the index of the last element in the array that is equal to the previous element. If