  return string.length;
}

// test cases
console.log(strlen('')); // 0
console.log(strlen('abc')); // 3
console.log(strlen('hello')); // 5
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen('')); // 0
console.log(strlen(''));