```
def Find_Min_Length(list_of_lists):
    return min(len(x) for x in list_of_lists)
```
This function uses a generator expression to calculate the length of each list in the list of lists. The built-in `min` function is then used to find the smallest of these lengths. 

For example, if we have the list `[[1],[1,2]]`, the function will return `1` because `1` is the smallest length in the list. 

The unit test `assert Find_Min_Length([[1],[1,2]]) == 1` ensures that the function is working correctly.  It checks that the function returns `1` when given the list `[[1],[1,2]]`.  If the function is not working correctly, the test will fail and an error message will be displayed.  This helps to ensure that the function is working correctly. 

This function can be used to find the length of the smallest list in a list of lists. It is a simple and efficient solution that is easy to understand and use.  It can be used in a variety of situations where you need to find the length of the smallest list in a list of lists.  For example, you might use it to find the length of the shortest list in a list of lists of numbers, or to find the length of the shortest list in a list of lists of strings.  It is a flexible and versatile function that can be used in a variety of situations.  It is also easy to modify and extend, which makes it a good choice for many applications.  It is a good choice for anyone who needs to find the length of the smallest list in a list of lists.  It is a simple and efficient solution that is easy to understand and use.  It can be used in a variety of situations where you need to find the length of the smallest list in a list of lists.  It is a good choice for many applications.  It is a good choice for anyone who needs to find the length of the smallest list in a list of lists.  It is a good choice for anyone who needs to find the length of the smallest list in a list of lists.  It is a good choice for anyone who needs to find the length of the smallest list in a list of lists.  It is a good choice for anyone who needs to find the length of the smallest list in a list of lists.  It is a good choice for anyone who needs to find the length of