
def histogram(test):
    test = test.split(" ")
    test = [x for x in test if x != ""]
    test = [x for x in test if x != " "]
    test = [x for x in test if x != "  "]
    test = [x for x in test if x != "   "]
    test = [x for x in test if x != "    "]
    test = [x for x in test if x != "     "]
    test = [x for x in test if x != "      "]
    test = [x for x in test if x != "       "]
    test = [x for x in test if x != "        "]
    test = [x for x in test if x != "         "]
    test = [x for x in test if x != "          "]
    test = [x for x in test if x != "           "]
    test = [x for x in test if x != "            "]
    test = [x for x in test if x != "             "]
    test = [x for x in test if x != "              "]
    test = [x for x in test if x != "               "]
    test = [x for x in test if x != "                "]
    test = [x for x in test if x != "                 "]
    test = [x for x in test if x != "                  "]
    test = [x for x in test if x != "                   "]
    test = [x for x in test if x != "                    "]
    test = [x for x in test if x != "                     "]
    test = [x for x in test if x != "                      "]
    test = [x for x in test if x != "                       "]
    test = [x for x in test if x != "                        "]
    test = [x for x in test if x != "                         "]
    test = [x for x in test if x != "                          "]
    test = [x for x in test if x != "                           "]
    test = [x for x in test if x !=