			xtr = new XmlTextReader (new StringReader (xml));
			xsr = new XmlTextReader (new StringReader (xsd));
			var s = new XmlReaderSettings ();
			s.Schemas.Add (XmlSchema.Read (xsr, null));
			s.ValidationType = ValidationType.Schema;
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address");
			xtr.ReadToDescendant ("address