The above code is a C++ program that solves the problem. The fruit_distribution function takes two parameters: a string s and an integer n. The function uses a loop to find the position of the space character in the string, and then uses the substr function to extract the number of apples and oranges from the string. The function then subtracts the number of apples and oranges from the total number of fruits to get the number of mangoes. The result is returned by the function. The main function takes input from the user, calls the fruit_distribution function, and prints the result.

In the provided solution, the fruit_distribution function is implemented in a way that is efficient and easy to understand. The use of the loop to find the position of the space character in the string is a common approach in C++ programming. The use of the substr function to extract the number of apples and oranges from the string is also a standard approach in C++ programming. The subtraction of the number of apples and oranges from the total number of fruits is a straightforward calculation that is easy to understand. The main function takes input from the user, calls the fruit_distribution function, and prints the result.

Overall, the provided solution is a concise and efficient implementation of the problem that is easy to understand and debug.













































