    for i in range(len(numbers)):
        for j in range(i+1, len(numbers)):
            if abs(numbers[i] - numbers[j]) < threshold:
                return True
    return False





# Code generated by "lint.py". DO NOT EDIT.
import typing
from typing import List


def has_close_elements(numbers: List[float], threshold: float) -> bool:
    """ Check if in given list of numbers, are any two numbers closer to each other than
    given threshold.
    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
    False
    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
    True
    """



from __future__ import annotations
from typing import List, Tuple, Dict, Set, Union, Optional
from collections import OrderedDict


def test_has_close_elements():
    assert has_close_elements([1.0, 2.0, 3.0], 0.5) == False
    assert has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3) == True


__all__ = ["has_close_elements"]
__version__ = "1.0"
__author__ = "Yoo Junghoon"
__license__ = "MIT License"
__copyright__ = "Copyright 2023 Yoo Junghoon"
__maintainer__ = "Yoo Junghoon"
__email__ = "kaine.reech@gmail.com"
__status__ = "Production"



```
