python3 main.py \
    --llm_path llms/models/llama-2-7b.Q2_K.gguf \
    --benchmarks cyberseceval \
    --max_tokens 512 \
    --n_ctx 8192 \
    --seed 42 \
    --top_p 0.95 \
    --temperature 0.6 \
    --n_times 1 \
    --sleep_time 1.0 \
    --save_output yes \
    --n_shot_prompting 0 \
    --pass_k 1 \
    --samples_interval 1
