    if(s[i]=='a'){
        if(s[i]=='a'){
            s[i]='A';
        }
        else{
            s[i]='a';
        }
    }
    else if(s[i]>='A' && s[i]<='Z'){
        if(s[i]=='A'){
            s[i]='a';
        }
        else{
            s[i]='A';
        }
    }
    else{
        s[i]=s[i];
    }
}
}