#include <bits/stdc++.h>
using namespace std;
#define ll long long int
#define pb push_back
#define mp make_pair
#define fi first
#define se second
#define mod 1000000007
#define pii pair<int,int>
#define vvi vector<vector<int>>
#define vi vector<int>
#define vvvi vector<vector<vector<int>>>
#define vpi vector<pair<int,int>>
#define vs vector<string>
#define vvb vector<vector<bool>>
#define vvp vector<vector<pair<int,int>>>
#define vvpi vector<vector<pair<int,int>>>
#define vppi vector<pair<int,vector<int>>>
#define mp3 unordered_map<string,pair<int,int>>
#define mp2 unordered_map<int,int>
#define mp1 unordered_map<int,int>
#define mll unordered_map<ll,ll>
#define mii unordered_map<int,int>
#define mci unordered_map<char,int>
#define smii map<int,int,greater<int>>
#define si set<int>
#define ss set<string>
#define sll set<ll>
#define sc set<char>
#define smp set<pair<int,int>>
#define ssi set<string>
#define sll set<ll>
#define ssc set<char>
#define smp set<pair<int,int>>
#define ssc set<char>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set<string>
#define smp set<pair<int,int>>
#define ssi set