    set<int> s;
    for(int i=0; i<l.size(); i++) {
        if(s.find(-l[i]) != s.end()) {
            return true;
        }
        s.insert(l[i]);
    }
    return false;
}  // O(n) solution
// This is the most efficient solution as it only needs a single pass over the vector.  It
// uses a set to store the elements we have seen so far. For each element, it checks if the
// set contains the negative of the current element. If it does, then we have found two
// elements that sum to zero. If it does not, then we add the current element to the set.  // Time complexity is O(n) where n is the size of the input vector.  // Space complexity is O(n) where n is the size of the input vector.  // This solution works for both positive and negative integers.  // This solution works for duplicate elements.  // This solution works for empty input vector.  // This solution works for input vector with single element.  // This solution works for input vector with all elements are zero.  // This solution works for input vector with all elements are positive.  // This solution works for input vector with all elements are negative.  // This solution works for input vector with all elements are equal.  // This solution works for input vector with all elements are different.  // This solution works for input vector with all elements are positive and negative.  // This solution works for input vector with all elements are zero and non zero.  // This solution works for input vector with all elements are positive and zero.  // This solution works for input vector with all elements are negative and zero.  // This solution works for input vector with all elements are positive and negative and zero.  // This solution works for input vector with all elements are positive and zero and negative.  // This solution works for input vector with all elements are negative and zero and positive.  // This solution works for input vector with all elements are zero and positive and negative.  // This solution works for input vector with all elements are zero and positive and zero and negative.  // This solution works for input vector with all elements are zero and negative and positive and negative.  // This solution works for input vector with all elements are zero and positive and zero and positive and negative.  // This solution works for input vector with all elements are zero and negative and zero and positive